name = "deen24id/odd_even"
version = "0.1.0"
description = "A module to test whether a number is odd or even."
authors = ["Imaduddin Haetami"]
repository = "https://github.com/deen24id/odd-even"
license = "MIT"
includes = ["README.md", "pesde.toml", "src/**", "LICENSE"]

[target]
environment = "lune"
lib = "src/lib/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
test = "scripts/test.luau"

[dev_dependencies]
frktest = { name = "itsfrank/frktest", version = "^0.0.2" }